2015-06-02 10:12:15 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:12:28 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:13:30 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:13:31 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:13:31 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:14:32 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:14:58 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:17:24 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:17:41 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:17:55 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:45 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:46 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:46 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:46 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:47 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:29:55 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:30:12 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:30:48 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:31:50 main.py[line:72] ERROR 数据写入失败:not all arguments converted during string formatting
2015-06-02 10:34:20 main.py[line:72] ERROR 数据写入失败:(1136, "Column count doesn't match value count at row 1")
2015-06-02 10:34:34 main.py[line:72] ERROR 数据写入失败:(1136, "Column count doesn't match value count at row 1")
2015-06-02 10:35:50 main.py[line:72] ERROR 数据写入失败:(1136, "Column count doesn't match value count at row 1")
2015-06-02 11:09:55 main.py[line:72] ERROR 数据写入失败:(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'passwd\': "\'202cb962ac59075b964b07152d234b70\'"},),birthday=\'5\xe6\x9c\x8821\',sex=\'\xe7\x94\xb7\',qq\' at line 2')
2015-06-02 18:35:33 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:19 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:24 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:29 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:32 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:32:34 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:33:18 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:33:19 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:33:21 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:34:08 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:34:12 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-02 20:34:13 main.py[line:96] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \n            item' at line 9")
2015-06-03 10:33:47 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'isstart' in 'field list'")
2015-06-03 10:33:49 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'isstart' in 'field list'")
2015-06-03 10:34:14 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'isstart' in 'field list'")
2015-06-03 18:00:35 main.py[line:74] ERROR 数据写入失败:not enough arguments for format string
2015-06-03 18:01:45 main.py[line:74] ERROR 数据写入失败:not enough arguments for format string
2015-06-08 13:55:21 main.py[line:74] ERROR 数据写入失败:(1146, "Table 'task.partment' doesn't exist")
2015-06-08 15:14:30 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:33 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:35 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:36 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:42 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:43 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:48 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:50 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:14:52 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:05 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:06 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:08 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:09 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:38 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:15:41 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:19 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:21 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:22 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:24 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:54 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:17:56 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:18:00 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:18:56 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:00 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:05 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:18 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:19 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:20 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:21 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:22 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:24 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:26 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:27 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:28 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:19:45 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:25:58 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:06 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:07 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:09 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:18 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:26:23 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:27:25 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:19 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:43 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:43 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:52 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:54 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:28:56 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:40 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:43 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:29:44 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:30:35 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:30:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:44 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:46 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:47 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:48 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:49 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:32:55 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:33:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 15:34:39 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'statid' in 'field list'")
2015-06-08 16:08:25 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:10:25 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:12:08 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:15:00 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:23:48 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'starttime' in 'field list'")
2015-06-08 16:25:06 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:25:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:25:17 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:25:20 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:25:48 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:26:46 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'items' in 'field list'")
2015-06-08 16:27:08 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'itype' in 'field list'")
2015-06-08 16:34:23 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:53:03 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:53:14 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:56:06 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-08 16:59:13 main.py[line:74] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3")
2015-06-10 16:20:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:20:22 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:21:05 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:21:09 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:21:15 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:21:56 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 16:29:17 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'password' in 'where clause'")
2015-06-10 20:07:11 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:07:46 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:07:47 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:07:48 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:08:24 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:08:28 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:08:34 main.py[line:98] ERROR 数据执行失败:not all arguments converted during string formatting
2015-06-10 20:28:31 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:28:33 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:28:34 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:29:32 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:29:33 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:29:37 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:29:40 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-10 20:31:22 main.py[line:98] ERROR 数据执行失败:(1054, "Unknown column 'Ui.name' in 'field list'")
2015-06-11 11:13:28 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:13:56 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:14:04 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:16:14 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:16:19 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:16:58 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:17:18 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:17:37 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:20:15 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:20:20 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:20:23 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:21:28 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:22:19 main.py[line:99] ERROR 数据执行失败:not enough arguments for format string
2015-06-11 11:22:41 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''WHERE 1=1'\n            ) AS t' at line 38")
2015-06-11 11:23:27 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''WHERE 1=1'\n            ) AS t' at line 38")
2015-06-11 11:23:30 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''WHERE 1=1'\n            ) AS t' at line 38")
2015-06-11 11:23:31 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''WHERE 1=1'\n            ) AS t' at line 38")
2015-06-11 11:42:09 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:18 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:21 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:33 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:35 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:42:39 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:43:47 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:43:53 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 11:44:01 main.py[line:99] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 1=1 and (T.userid=18 or T.assistid=18 )\n            ORDER BY\n             ' at line 39")
2015-06-11 14:27:21 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:23 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:24 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:25 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:25 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:26 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:36 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:55 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:56 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:57 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:27:57 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:28:02 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:28:04 main.py[line:99] ERROR 数据执行失败:(1054, "Unknown column 'recovery' in 'where clause'")
2015-06-11 14:50:53 main.py[line:75] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'del_status=0\n        WHERE\n            id='5'' at line 5")
2015-06-11 14:52:05 main.py[line:75] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'del_status=0\n        WHERE\n            id='5'' at line 5")
2015-06-11 15:21:23 main.py[line:77] ERROR 数据写入失败:not enough arguments for format string
2015-06-11 15:22:00 main.py[line:73] ERROR 数据写入失败:not enough arguments for format string
2015-06-11 15:36:14 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 15:38:07 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 15:40:13 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 15:41:08 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:03:15 main.py[line:97] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:09:42 main.py[line:98] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:12:24 main.py[line:94] ERROR 数据执行失败:(1066, "Not unique table/alias: 'U'")
2015-06-11 16:12:27 main.py[line:94] ERROR 数据执行失败:(1066, "Not unique table/alias: 'U'")
2015-06-11 16:12:29 main.py[line:94] ERROR 数据执行失败:(1066, "Not unique table/alias: 'U'")
2015-06-11 16:15:34 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:36 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:36 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:37 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:38 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:39 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:40 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:41 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:44 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:45 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:46 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:46 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:15:53 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:13 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:15 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:16 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:19 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:28 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:16:34 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:29 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:30 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:31 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:31 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:31 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:32 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:19:32 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:20:42 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-11 16:21:00 main.py[line:94] ERROR 数据执行失败:(1052, "Column 'del_status' in where clause is ambiguous")
2015-06-12 10:00:27 main.py[line:94] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM\n            item AS I\n            LEFT OUTER JOIN user AS U on I.userid = U' at line 11")
2018-04-17 21:36:41 main.py[line:95] ERROR 数据执行失败:'long' object is not iterable
2018-04-17 21:36:46 main.py[line:95] ERROR 数据执行失败:'long' object is not iterable
2018-04-17 21:36:48 main.py[line:95] ERROR 数据执行失败:'long' object is not iterable
2018-04-17 21:53:41 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-17 23:12:25 main.py[line:95] ERROR 数据执行失败:'long' object is not iterable
2018-04-17 23:13:18 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-17 23:14:13 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-17 23:14:23 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-17 23:14:29 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-17 23:14:29 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-17 23:14:36 main.py[line:95] ERROR 数据执行失败:'long' object is not iterable
2018-04-17 23:30:06 main.py[line:95] ERROR 数据执行失败:'long' object is not iterable
2018-04-17 23:30:16 main.py[line:95] ERROR 数据执行失败:'long' object is not iterable
2018-04-18 23:10:35 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-18 23:11:28 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-18 23:11:29 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-18 23:22:43 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-18 23:23:17 main.py[line:95] ERROR 数据执行失败:not enough arguments for format string
2018-04-18 23:23:19 main.py[line:95] ERROR 数据执行失败:not enough arguments for format string
2018-04-18 23:23:46 main.py[line:95] ERROR 数据执行失败:not enough arguments for format string
2018-04-18 23:24:08 main.py[line:95] ERROR 数据执行失败:not enough arguments for format string
2018-04-18 23:24:23 main.py[line:95] ERROR 数据执行失败:not enough arguments for format string
2018-04-18 23:26:36 main.py[line:95] ERROR 数据执行失败:not enough arguments for format string
2018-04-18 23:32:49 main.py[line:95] ERROR 数据执行失败:'int' object is not iterable
2018-04-18 23:36:46 main.py[line:95] ERROR 数据执行失败:'int' object is not iterable
2018-04-18 23:37:42 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-18 23:37:42 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-18 23:41:40 main.py[line:95] ERROR 数据执行失败:'int' object is not iterable
2018-04-18 23:42:43 main.py[line:95] ERROR 数据执行失败:'int' object is not iterable
2018-04-18 23:43:02 main.py[line:95] ERROR 数据执行失败:'int' object is not iterable
2018-04-18 23:44:01 main.py[line:95] ERROR 数据执行失败:'int' object is not iterable
2018-04-23 19:45:46 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-23 19:46:32 main.py[line:95] ERROR 数据执行失败:not all arguments converted during string formatting
2018-04-24 19:43:34 main.py[line:88] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-04-24 19:43:40 main.py[line:88] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-04-24 19:43:55 main.py[line:88] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-04-24 19:44:22 main.py[line:88] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-04-27 20:58:18 main.py[line:88] ERROR 数据库连接失败:(1049, "Unknown database 'jingsai'")
2018-04-27 20:58:24 main.py[line:88] ERROR 数据库连接失败:(1049, "Unknown database 'jingsai'")
2018-04-29 11:35:54 main.py[line:88] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-05-10 23:25:02 main.py[line:75] ERROR 数据写入失败:(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'LDle:I8(Node20)\': "\'LDle:I8(Add32(LDle:I32(Add32(Add32(REG_INI,0x00000070),0x00\' at line 3')
2018-05-10 23:31:12 main.py[line:75] ERROR 数据写入失败:(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'LDle:I8(Node20)\': "\'LDle:I8(Add32(LDle:I32(Add32(Add32(REG_INI,0x00000070),0x00\' at line 3')
2018-05-10 23:33:34 main.py[line:75] ERROR 数据写入失败:(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'LDle:I8(Node20)\': "\'LDle:I8(Add32(LDle:I32(Add32(Add32(REG_INI,0x00000070),0x00\' at line 3')
2018-05-10 23:40:26 main.py[line:75] ERROR 数据写入失败:(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'LDle:I8(Node20)\': "\'LDle:I8(Add32(LDle:I32(Add32(Add32(REG_INI,0x00000070),0x00\' at line 3')
2018-05-10 23:41:27 main.py[line:76] ERROR 数据写入失败:(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'LDle:I8(Node20)\': "\'LDle:I8(Add32(LDle:I32(Add32(Add32(REG_INI,0x00000070),0x00\' at line 3')
2018-05-10 23:43:31 main.py[line:100] ERROR 数据执行失败:(1054, "Unknown column 'T.status' in 'field list'")
2018-05-10 23:44:41 main.py[line:100] ERROR 数据执行失败:(1054, "Unknown column 'T.inputdate' in 'field list'")
2018-05-10 23:47:08 main.py[line:100] ERROR 数据执行失败:(1054, "Unknown column 'T.inputdate' in 'field list'")
2018-05-10 23:47:35 main.py[line:100] ERROR 数据执行失败:(1054, "Unknown column 'T.inputdate' in 'field list'")
2018-05-11 00:03:01 main.py[line:100] ERROR 数据执行失败:(1054, "Unknown column 'T.inputdate' in 'field list'")
2018-05-11 22:54:46 main.py[line:100] ERROR 数据执行失败:(1054, "Unknown column 'T.inputdate' in 'field list'")
2018-05-11 22:57:15 main.py[line:100] ERROR 数据执行失败:(1054, "Unknown column 'T.inputdate' in 'field list'")
2018-05-11 22:57:18 main.py[line:100] ERROR 数据执行失败:(1054, "Unknown column 'T.inputdate' in 'field list'")
2018-05-11 23:24:38 main.py[line:100] ERROR 数据执行失败:(1054, "Unknown column 'T.inputdate' in 'field list'")
2018-05-11 23:57:25 main.py[line:100] ERROR 数据执行失败:(1146, "Table 'jingsai.department' doesn't exist")
2018-05-11 23:58:56 main.py[line:100] ERROR 数据执行失败:(1146, "Table 'jingsai.department' doesn't exist")
2018-05-14 14:48:32 main.py[line:94] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-05-28 10:13:32 main.py[line:101] ERROR 数据执行失败:(1146, "Table 'jingsai.item' doesn't exist")
2018-05-28 10:13:32 main.py[line:101] ERROR 数据执行失败:(1146, "Table 'jingsai.department' doesn't exist")
2018-05-28 10:13:32 main.py[line:101] ERROR 数据执行失败:not all arguments converted during string formatting
2018-05-28 11:59:25 main.py[line:101] ERROR 数据执行失败:(1054, "Unknown column 'T.userid' in 'on clause'")
2018-05-28 11:59:47 main.py[line:101] ERROR 数据执行失败:(1054, "Unknown column 'T.userid' in 'on clause'")
2018-05-28 16:18:02 main.py[line:94] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-05-30 10:50:51 main.py[line:101] ERROR 数据执行失败:(1146, "Table 'jingsai.department' doesn't exist")
2018-05-30 10:59:04 main.py[line:101] ERROR 数据执行失败:(1146, "Table 'jingsai.department' doesn't exist")
2018-05-30 11:00:40 main.py[line:101] ERROR 数据执行失败:(1146, "Table 'jingsai.department' doesn't exist")
2018-05-30 11:12:34 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-05-30 11:12:37 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-05-30 11:13:09 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-05-30 11:15:02 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-05-30 11:17:14 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-05-30 11:18:01 main.py[line:77] ERROR 数据写入失败:not all arguments converted during string formatting
2018-06-03 20:59:37 main.py[line:94] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-07-13 23:04:14 main.py[line:87] ERROR 数据库连接失败:(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 0")
2018-07-13 23:04:20 main.py[line:87] ERROR 数据库连接失败:(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 0")
2018-07-14 09:56:05 main.py[line:87] ERROR 数据库连接失败:(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 2")
2018-07-14 09:56:36 main.py[line:87] ERROR 数据库连接失败:(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 0")
2018-07-14 13:27:44 main.py[line:87] ERROR 数据库连接失败:(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 2")
2018-07-14 13:27:54 main.py[line:87] ERROR 数据库连接失败:(2003, "Can't connect to MySQL server on 'localhost' (10061)")
2018-07-14 17:14:47 main.py[line:87] ERROR 数据库连接失败:(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 2")
2018-07-14 17:14:50 main.py[line:87] ERROR 数据库连接失败:(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 2")
2018-07-15 21:38:39 main.py[line:87] ERROR 数据库连接失败:(2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 0")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80484ac','\xe5\x86\x99\xe6\x96\x87\xe4\xbb\xb6')' at line 2")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80485e9','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\xb0\xe7\x94\xa8\xe6\x88\xb7')' at line 2")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x804845c','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\x87\xe4\xbb\xb6')' at line 2")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x8048508','\xe5\x88\xa0\xe9\x99\xa4\xe7\x9b\xae\xe5\xbd\x95')' at line 2")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80485a3','\xe6\x99\xae\xe9\x80\x9a\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 2")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x8048568','\xe6\x9e\x9a\xe4\xb8\xbe\xe7\x9b\xae\xe5\xbd\x95')' at line 2")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80485c6','\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 2")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80484de','\xe5\x88\xa0\xe9\x99\xa4\xe6\x96\x87\xe4\xbb\xb6')' at line 2")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x804853e','\xe8\xaf\xbb\xe6\x96\x87\xe4\xbb\xb6')' at line 2")
2018-07-20 14:46:52 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x8048486','\xe5\x88\x9b\xe5\xbb\xba\xe7\x9b\xae\xe5\xbd\x95')' at line 2")
2018-07-20 14:48:50 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80484ac','\xe5\x86\x99\xe6\x96\x87\xe4\xbb\xb6')' at line 2")
2018-07-20 14:48:51 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80485e9','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\xb0\xe7\x94\xa8\xe6\x88\xb7')' at line 2")
2018-07-20 14:48:51 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x804845c','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\x87\xe4\xbb\xb6')' at line 2")
2018-07-20 14:48:51 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x8048508','\xe5\x88\xa0\xe9\x99\xa4\xe7\x9b\xae\xe5\xbd\x95')' at line 2")
2018-07-20 14:48:51 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80485a3','\xe6\x99\xae\xe9\x80\x9a\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 2")
2018-07-20 14:48:51 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x8048568','\xe6\x9e\x9a\xe4\xb8\xbe\xe7\x9b\xae\xe5\xbd\x95')' at line 2")
2018-07-20 14:48:51 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80485c6','\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 2")
2018-07-20 14:48:51 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x80484de','\xe5\x88\xa0\xe9\x99\xa4\xe6\x96\x87\xe4\xbb\xb6')' at line 2")
2018-07-20 14:48:51 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x804853e','\xe8\xaf\xbb\xe6\x96\x87\xe4\xbb\xb6')' at line 2")
2018-07-20 14:48:51 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior)\n        VALUES('0x8048486','\xe5\x88\x9b\xe5\xbb\xba\xe7\x9b\xae\xe5\xbd\x95')' at line 2")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x80484ac','\xe5\x86\x99\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x80485e9','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\xb0\xe7\x94\xa8\xe6\x88\xb7')' at line 1")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x804845c','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x8048508','\xe5\x88\xa0\xe9\x99\xa4\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x80485a3','\xe6\x99\xae\xe9\x80\x9a\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 1")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x8048568','\xe6\x9e\x9a\xe4\xb8\xbe\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x80485c6','\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 1")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x80484de','\xe5\x88\xa0\xe9\x99\xa4\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x804853e','\xe8\xaf\xbb\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 14:51:41 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behavior) VALUES ('0x8048486','\xe5\x88\x9b\xe5\xbb\xba\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x80484ac','\xe5\x86\x99\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x80485e9','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\xb0\xe7\x94\xa8\xe6\x88\xb7')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x804845c','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x8048508','\xe5\x88\xa0\xe9\x99\xa4\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x80485a3','\xe6\x99\xae\xe9\x80\x9a\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x8048568','\xe6\x9e\x9a\xe4\xb8\xbe\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x80485c6','\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x80484de','\xe5\x88\xa0\xe9\x99\xa4\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x804853e','\xe8\xaf\xbb\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 14:59:29 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors) VALUES ('0x8048486','\xe5\x88\x9b\xe5\xbb\xba\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:27:18 main.py[line:70] ERROR 数据写入失败:sequence item 0: expected string, dict found
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:30:44 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ('<built-in method values of dict object at 0x07AFCC90>' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x80484ac','\xe5\x86\x99\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x80485e9','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\xb0\xe7\x94\xa8\xe6\x88\xb7')' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x804845c','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x8048508','\xe5\x88\xa0\xe9\x99\xa4\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x80485a3','\xe6\x99\xae\xe9\x80\x9a\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x8048568','\xe6\x9e\x9a\xe4\xb8\xbe\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x80485c6','\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x80484de','\xe5\x88\xa0\xe9\x99\xa4\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x804853e','\xe8\xaf\xbb\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 15:31:46 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES ((85),'0x8048486','\xe5\x88\x9b\xe5\xbb\xba\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x80484ac','\xe5\x86\x99\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x80485e9','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\xb0\xe7\x94\xa8\xe6\x88\xb7')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x804845c','\xe5\x88\x9b\xe5\xbb\xba\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x8048508','\xe5\x88\xa0\xe9\x99\xa4\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x80485a3','\xe6\x99\xae\xe9\x80\x9a\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x8048568','\xe6\x9e\x9a\xe4\xb8\xbe\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x80485c6','\xe7\x94\xa8\xe6\x88\xb7\xe6\x89\xa7\xe8\xa1\x8c\xe5\x91\xbd\xe4\xbb\xa4')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x80484de','\xe5\x88\xa0\xe9\x99\xa4\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x804853e','\xe8\xaf\xbb\xe6\x96\x87\xe4\xbb\xb6')' at line 1")
2018-07-20 15:34:06 main.py[line:70] ERROR 数据写入失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out`,`behaviors`) VALUES (86,'0x8048486','\xe5\x88\x9b\xe5\xbb\xba\xe7\x9b\xae\xe5\xbd\x95')' at line 1")
2018-07-20 15:42:52 main.py[line:94] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors FROM behavior WHERE id = 87' at line 1")
2018-07-20 15:46:15 main.py[line:94] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors FROM behavior WHERE id = 88' at line 1")
2018-07-20 15:47:47 main.py[line:94] ERROR 数据执行失败:(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'out,behaviors FROM behavior WHERE id = 88' at line 1")
